### ISSUE TITLE
No module named address

### ISSUE THREAD

**Issue by Backo11** [Nick-Vinesmoke/Heat_CLIPPER#1]
Traceback (most recent call last):
  File "HeatClipper.py", line 3, in <module>
ModuleNotFoundError: No module named 'addresses'

Any help?

**Comment by Nick-Vinesmoke** [comment]
I fixed it (https://github.com/Nick-Vinesmoke/Heat_CLIPPER/commit/476357a51a69e71e5b0d9d4cc089bbc365310e68). Try again

**Comment by Nick-Vinesmoke** [comment]
thx for ur issue
